-- Migration 053: content-type search + category/comment embeddings for RAG.
--
-- This is a forward-only schema/search migration. It intentionally does not
-- backfill embeddings: content_types.embedding is filled by ContentTypeService
-- on category create/update; user_files.comment_embedding is filled only for
-- manual comments by RAG ingest.
--
-- Search behavior:
--   * list_categories/search_content_types remains trigram search over active
--     content_types.name.
--   * concrete document search is TSV-first over user_files.tsv. The TSV column
--     includes filename, comment, and summary.
--   * abstract document search ranks by vec_dist - comment_dist * 0.15, where
--     comment_dist is sourced from a MATERIALIZED CTE of per-category cosine
--     distances (computed once per call). Files without a category use their own
--     comment_embedding distance; files with neither get comment_dist = 0.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_content_types_name_trgm
    ON content_types USING GIN (name gin_trgm_ops)
    WHERE is_active = true;

-- search_content_types(p_org_id, p_query, p_threshold)
-- Returns active content types for the org whose name is similar to p_query.
-- p_threshold: similarity threshold in [0,1]; lower = looser match (default 0.1).
CREATE OR REPLACE FUNCTION search_content_types(
    p_org_id    uuid,
    p_query     text,
    p_threshold real DEFAULT 0.1
)
RETURNS TABLE (
    id          uuid,
    org_id      uuid,
    name        text,
    description text,
    is_active   boolean,
    created_at  timestamptz,
    updated_at  timestamptz,
    similarity  real
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN QUERY
    SELECT
        ct.id,
        ct.org_id,
        ct.name,
        ct.description,
        ct.is_active,
        ct.created_at,
        ct.updated_at,
        similarity(ct.name, p_query) AS similarity
    FROM content_types ct
    WHERE ct.org_id = p_org_id
      AND ct.is_active = true
      AND similarity(ct.name, p_query) >= p_threshold
    ORDER BY similarity(ct.name, p_query) DESC, ct.name;
END;
$$;

COMMENT ON FUNCTION search_content_types(uuid, text, real) IS
    'Fuzzy trigram search over active content_types names for an org. '
    'p_threshold controls match looseness: lower = more results (default 0.1).';

-- Add list_categories tool to the doc_search role. Idempotent.
UPDATE roles
SET tools      = tools || '["list_categories"]'::jsonb,
    updated_at = NOW()
WHERE code = 'doc_search'
  AND NOT (tools @> '["list_categories"]'::jsonb);

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE content_types
    ADD COLUMN IF NOT EXISTS embedding vector(1024);

COMMENT ON COLUMN content_types.embedding IS
    'Name+description embedding for category-aware RAG document search. '
    'Generated by ContentTypeService; not mirrored into user_files.';

CREATE INDEX IF NOT EXISTS idx_content_types_embedding_hnsw
    ON content_types USING hnsw (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL AND is_active = true;

ALTER TABLE user_files
    ADD COLUMN IF NOT EXISTS comment_embedding vector(1024);

COMMENT ON COLUMN user_files.comment_embedding IS
    'Manual file-comment embedding for RAG search. '
    'Category-backed files use content_types.embedding via join instead.';

CREATE INDEX IF NOT EXISTS idx_user_files_comment_embedding_hnsw
    ON user_files USING hnsw (comment_embedding vector_cosine_ops)
    WHERE comment_embedding IS NOT NULL AND is_active = true;

-- Recreate generated TSV to ensure comments participate in concrete document search.
-- Weights are ordered D,C,B,A in ts_rank:
--   original_filename -> A = strongest lexical signal
--   comment           -> B = user/category-provided business context
--   summary           -> C = broader generated context
DROP INDEX IF EXISTS user_files_tsv_gin_idx;

ALTER TABLE user_files
    DROP COLUMN IF EXISTS tsv;

ALTER TABLE user_files
    ADD COLUMN tsv tsvector
        GENERATED ALWAYS AS (
            setweight(to_tsvector('russian', coalesce(original_filename, '')), 'A') ||
            setweight(to_tsvector('russian', coalesce(comment,           '')), 'B') ||
            setweight(to_tsvector('russian', coalesce(summary,           '')), 'C')
        ) STORED;

CREATE INDEX IF NOT EXISTS user_files_tsv_gin_idx
    ON user_files USING GIN (tsv)
    WHERE is_active = true;

CREATE OR REPLACE FUNCTION sync_content_type_description_to_file_comments()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.description IS DISTINCT FROM OLD.description THEN
        UPDATE user_files
        SET comment = NEW.description,
            updated_at = NOW()
        WHERE content_type_id = NEW.id
          AND is_active = true;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_content_types_description_to_file_comments ON content_types;

CREATE TRIGGER trg_content_types_description_to_file_comments
AFTER UPDATE OF description ON content_types
FOR EACH ROW
EXECUTE FUNCTION sync_content_type_description_to_file_comments();

COMMENT ON FUNCTION sync_content_type_description_to_file_comments() IS
    'Mirrors content_types.description into user_files.comment for category-backed files only. '
    'Does not mirror embeddings; abstract search reads category distances from a pre-built CTE.';

DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer);
DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer, boolean);
DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer, boolean, uuid);
DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer, boolean, uuid, boolean);
DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer, boolean, uuid, boolean, text);
DROP FUNCTION IF EXISTS search_related_docs(uuid, uuid, text, vector, integer, boolean, uuid, boolean, text, uuid);

CREATE FUNCTION search_related_docs(
  p_org_id           uuid,
  p_user_id          uuid,
  p_query            text,
  p_query_emb        vector(1024),
  p_top_k            integer,
  p_is_admin         boolean DEFAULT false,
  p_filter_user_id   uuid    DEFAULT NULL,
  p_exclude_images   boolean DEFAULT true,
  p_search_mode      text    DEFAULT 'abstract',
  p_content_type_id  uuid    DEFAULT NULL
)
RETURNS TABLE (
  doc_id                    uuid,
  org_id                    uuid,
  user_id                   uuid,
  doc_title                 varchar(500),
  summary                   text,
  comment                   text,
  content_type_id           uuid,
  content_type_name         text,
  content_type_description  text,
  uploaded_at               timestamptz,
  created_at                date,
  vec_dist                  double precision,
  tsv_score                 real,
  mode_used                 text
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_tsquery tsquery;
  v_pool    integer;
BEGIN
  v_pool := GREATEST(p_top_k * 10, 50);
  v_tsquery := plainto_tsquery('russian', p_query);

  IF p_search_mode NOT IN ('concrete', 'abstract') THEN
    RAISE EXCEPTION 'search_related_docs p_search_mode must be concrete or abstract, got %', p_search_mode;
  END IF;

  IF p_search_mode = 'concrete' THEN
    RETURN QUERY
    WITH lex AS (
      SELECT
        uf.id AS doc_id,
        ts_rank(ARRAY[0.1, 0.3, 0.6, 1.0]::real[], uf.tsv, v_tsquery, 1) AS tsv_score
      FROM user_files uf
      WHERE uf.org_id    = p_org_id
        AND (p_filter_user_id IS NULL OR uf.user_id = p_filter_user_id)
        AND (p_content_type_id IS NULL OR uf.content_type_id = p_content_type_id)
        AND (uf.is_public OR uf.user_id = p_user_id OR p_is_admin)
        AND (
          NOT p_exclude_images
          OR (
            lower(COALESCE(uf.file_type, '')) NOT IN ('jpg', 'jpeg', 'png', 'gif', 'webp')
            AND lower(COALESCE(uf.original_filename, '')) NOT LIKE ALL(ARRAY['%.jpg', '%.jpeg', '%.png', '%.gif', '%.webp'])
          )
        )
        AND uf.is_active = true
        AND uf.tsv @@ v_tsquery
      ORDER BY ts_rank(ARRAY[0.1, 0.3, 0.6, 1.0]::real[], uf.tsv, v_tsquery, 1) DESC
      LIMIT v_pool
    )
    SELECT
      uf.id                                  AS doc_id,
      uf.org_id                              AS org_id,
      uf.user_id                             AS user_id,
      uf.original_filename                   AS doc_title,
      uf.summary                             AS summary,
      uf.comment                             AS comment,
      uf.content_type_id                     AS content_type_id,
      ct.name                                AS content_type_name,
      ct.description                         AS content_type_description,
      uf.created_at                          AS uploaded_at,
      uf.created_at::date                    AS created_at,
      (uf.summary_embedding <=> p_query_emb) AS vec_dist,
      l.tsv_score                            AS tsv_score,
      'concrete'::text                       AS mode_used
    FROM lex l
    JOIN user_files uf ON uf.id = l.doc_id
    LEFT JOIN content_types ct ON ct.id = uf.content_type_id AND ct.org_id = p_org_id
    WHERE uf.summary_embedding IS NOT NULL AND l.tsv_score > 0
    ORDER BY l.tsv_score DESC, (uf.summary_embedding <=> p_query_emb) ASC
    LIMIT p_top_k;

  ELSE
    RETURN QUERY
    -- _category_dists is MATERIALIZED so each category's distance to the query
    -- is computed once and reused per file. A plain CTE would suffice here since
    -- only one branch executes per call (no cross-branch sharing needed); we chose
    -- MATERIALIZED over TEMP TABLE specifically because it avoids DDL overhead and
    -- catalog pollution while still guaranteeing a single evaluation.
    WITH _category_dists AS MATERIALIZED (
      SELECT
        ct.id          AS content_type_id,
        ct.name        AS content_type_name,
        ct.description AS content_type_description,
        (ct.embedding <=> p_query_emb)::double precision AS cat_dist
      FROM content_types ct
      WHERE ct.org_id    = p_org_id
        AND ct.is_active = true
        AND ct.embedding IS NOT NULL
    ),
    eligible_files AS (
      SELECT
        uf.id,
        uf.content_type_id,
        uf.summary_embedding,
        uf.comment_embedding
      FROM user_files uf
      WHERE uf.org_id    = p_org_id
        AND (p_filter_user_id IS NULL OR uf.user_id = p_filter_user_id)
        AND (p_content_type_id IS NULL OR uf.content_type_id = p_content_type_id)
        AND (uf.is_public OR uf.user_id = p_user_id OR p_is_admin)
        AND (
          NOT p_exclude_images
          OR (
            lower(COALESCE(uf.file_type, '')) NOT IN ('jpg', 'jpeg', 'png', 'gif', 'webp')
            AND lower(COALESCE(uf.original_filename, '')) NOT LIKE ALL(ARRAY['%.jpg', '%.jpeg', '%.png', '%.gif', '%.webp'])
          )
        )
        AND uf.is_active = true
        AND uf.summary_embedding IS NOT NULL
    ),
    candidates AS (
      SELECT ef.id AS doc_id
      FROM eligible_files ef
      ORDER BY ef.summary_embedding <=> p_query_emb
      LIMIT v_pool
    ),
    doc_vectors AS (
      SELECT
        uf.id                  AS doc_id,
        uf.org_id              AS org_id,
        uf.user_id             AS user_id,
        uf.original_filename   AS doc_title,
        uf.summary             AS summary,
        uf.comment             AS comment,
        uf.content_type_id          AS content_type_id,
        cd.content_type_name        AS content_type_name,
        cd.content_type_description AS content_type_description,
        uf.created_at               AS uploaded_at,
        uf.created_at::date         AS created_at,
        uf.tsv                      AS tsv,
        (uf.summary_embedding <=> p_query_emb) AS vec_dist,
        -- comment_dist: use cached category distance when the file has a category,
        -- fall back to the file's own comment_embedding distance if no category,
        -- or 0 if neither exists.
        CASE
          WHEN uf.content_type_id IS NOT NULL THEN COALESCE(cd.cat_dist, 0)
          WHEN uf.comment_embedding IS NOT NULL THEN (uf.comment_embedding <=> p_query_emb)
          ELSE 0
        END AS comment_dist
      FROM candidates c
      JOIN user_files uf ON uf.id = c.doc_id
      LEFT JOIN _category_dists cd ON cd.content_type_id = uf.content_type_id
    ),
    scored AS (
      SELECT
        dv.*,
        CASE
          WHEN dv.tsv @@ v_tsquery THEN ts_rank(ARRAY[0.1, 0.3, 0.6, 1.0]::real[], dv.tsv, v_tsquery)
          ELSE 0
        END AS tsv_score,
        dv.vec_dist - dv.comment_dist * 0.15 AS final_score
      FROM doc_vectors dv
    )
    SELECT
      s.doc_id                AS doc_id,
      s.org_id                AS org_id,
      s.user_id               AS user_id,
      s.doc_title             AS doc_title,
      s.summary               AS summary,
      s.comment               AS comment,
      s.content_type_id       AS content_type_id,
      s.content_type_name     AS content_type_name,
      s.content_type_description AS content_type_description,
      s.uploaded_at           AS uploaded_at,
      s.created_at            AS created_at,
      s.vec_dist              AS vec_dist,
      s.tsv_score             AS tsv_score,
      'abstract'::text        AS mode_used
    FROM scored s
    WHERE s.vec_dist < 0.65
    ORDER BY s.final_score ASC, s.tsv_score DESC
    LIMIT p_top_k;
  END IF;
END;
$$;

COMMENT ON FUNCTION search_related_docs(uuid, uuid, text, vector, integer, boolean, uuid, boolean, text, uuid) IS
  'p_search_mode chooses concrete TSV-first or abstract vector-first search. '
  'Abstract mode scores by vec_dist - comment_dist * 0.15. comment_dist comes from a '
  'MATERIALIZED CTE of per-category cosine distances (evaluated once per call); files '
  'without a category fall back to their own comment_embedding distance, or 0 if absent. '
  'p_is_admin allows org admins to search all active documents including private files. '
  'p_filter_user_id narrows to one file owner. '
  'p_exclude_images omits image files. '
  'p_content_type_id narrows to one content type (NULL = no filter).';
