"""
Correction Rule Model

Represents a correction rule created when a user rejects an AI response.
Rules accumulate and help the role improve over time via RAG.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4


@dataclass
class CorrectionRule:
    """
    Correction rule created from user rejection of AI response.

    Flow:
    1. Someone sends @@user message, AI role responds
    2. User reviews the response and rejects it with correction_text
    3. CorrectionRule is created with the original Q&A + correction
    4. rule_text is generated by LLM (concise instruction for the role)
    5. On future requests, relevant rules are loaded and injected into prompt
    """
    id: UUID = field(default_factory=uuid4)
    role_id: UUID = field(default_factory=uuid4)
    org_id: UUID = field(default_factory=uuid4)
    original_message_id: UUID = field(default_factory=uuid4)  # User question
    ai_message_id: UUID = field(default_factory=uuid4)        # AI answer that was rejected
    chat_id: UUID = field(default_factory=uuid4)
    user_question: str = ""
    ai_answer: str = ""
    correction_text: str = ""       # What user said was wrong
    rule_text: Optional[str] = None  # LLM-generated rule for the role
    created_by_user_id: UUID = field(default_factory=uuid4)
    is_active: bool = True
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "role_id": str(self.role_id),
            "org_id": str(self.org_id),
            "original_message_id": str(self.original_message_id),
            "ai_message_id": str(self.ai_message_id),
            "chat_id": str(self.chat_id),
            "user_question": self.user_question,
            "ai_answer": self.ai_answer,
            "correction_text": self.correction_text,
            "rule_text": self.rule_text,
            "created_by_user_id": str(self.created_by_user_id),
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CorrectionRule":
        return cls(
            id=UUID(data["id"]) if isinstance(data.get("id"), str) else data.get("id", uuid4()),
            role_id=UUID(data["role_id"]) if isinstance(data.get("role_id"), str) else data.get("role_id", uuid4()),
            org_id=UUID(data["org_id"]) if isinstance(data.get("org_id"), str) else data.get("org_id", uuid4()),
            original_message_id=UUID(data["original_message_id"]) if isinstance(data.get("original_message_id"), str) else data.get("original_message_id", uuid4()),
            ai_message_id=UUID(data["ai_message_id"]) if isinstance(data.get("ai_message_id"), str) else data.get("ai_message_id", uuid4()),
            chat_id=UUID(data["chat_id"]) if isinstance(data.get("chat_id"), str) else data.get("chat_id", uuid4()),
            user_question=data.get("user_question", ""),
            ai_answer=data.get("ai_answer", ""),
            correction_text=data.get("correction_text", ""),
            rule_text=data.get("rule_text"),
            created_by_user_id=UUID(data["created_by_user_id"]) if isinstance(data.get("created_by_user_id"), str) else data.get("created_by_user_id", uuid4()),
            is_active=data.get("is_active", True),
            created_at=datetime.fromisoformat(data["created_at"]) if isinstance(data.get("created_at"), str) else data.get("created_at", datetime.utcnow()),
            updated_at=datetime.fromisoformat(data["updated_at"]) if isinstance(data.get("updated_at"), str) else data.get("updated_at", datetime.utcnow()),
        )
