"""
Task Report Model

AI-generated evening reports for managers.
"""
from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Optional
from uuid import UUID, uuid4


@dataclass
class TaskReport:
    """
    Evening report generated by AI for a manager.
    Aggregates task poll responses from employees.
    """
    id: UUID = field(default_factory=uuid4)
    org_id: UUID = field(default_factory=uuid4)
    generated_for_user_id: UUID = field(default_factory=uuid4)  # manager
    report_date: date = field(default_factory=date.today)
    content: str = ""                                            # AI-generated text
    task_summaries: list = field(default_factory=list)            # structured data
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert to dictionary for API response"""
        return {
            "id": str(self.id),
            "org_id": str(self.org_id),
            "generated_for_user_id": str(self.generated_for_user_id),
            "report_date": self.report_date.isoformat(),
            "content": self.content,
            "task_summaries": self.task_summaries,
            "created_at": self.created_at.isoformat(),
        }
