"""Unified logger для движка rugpt.                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        
Публичный API:                                                                                                                                                                                                                                                           
- get_logger(component) — фабрика-кэш, возвращает EngUnifiedLogger.
- set_user_id, get_user_id — переэкспорт для удобства.                                                                                                                                                                                                                     
"""
from typing import Dict                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        
from .eng import EngUnifiedLogger                                                                                                                                                                                                                                          
from src.engine.logging_context import set_user_id, get_user_id
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                        
_loggers: Dict[str, EngUnifiedLogger] = {}                                                                                                                                                                                                                               

                                                                                                                                                                                                                                                                            
def get_logger(component: str) -> EngUnifiedLogger:
    """Вернуть logger для компонента. Объект кэшируется по имени.                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                            
    При повторных вызовах с тем же `component` возвращает тот же объект,                                                                                                                                                                                                 
    чтобы не плодить дубликаты FileHandler'ов на один файл.                                                                                                                                                                                                                
    """                                                                                                                                                                                                                                                                    
    if component not in _loggers:                                                                                                                                                                                                                                          
        _loggers[component] = EngUnifiedLogger(component)                                                                                                                                                                                                                  
    return _loggers[component]                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                            
__all__ = ["get_logger", "set_user_id", "get_user_id"]    